# Generated by Django 4.1.7 on 2023-03-03 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareProviderLocation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management_interface.basemodel')),
                ('name', models.CharField(help_text='Helping Hands Wantage', max_length=256)),
                ('email', models.EmailField(db_index=True, help_text='example@nhs.net', max_length=254, unique=True)),
                ('ods_code', models.CharField(help_text='VNJNK', max_length=16, unique=True)),
                ('cqc_location_id', models.CharField(help_text='1-11086090064', max_length=128, unique=True)),
            ],
            bases=('management_interface.basemodel',),
        ),
        migrations.CreateModel(
            name='RegisteredManager',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management_interface.basemodel')),
                ('given_name', models.CharField(db_index=True, help_text='Aislinn', max_length=256)),
                ('family_name', models.CharField(db_index=True, help_text='Mullen', max_length=256)),
                ('email', models.EmailField(db_index=True, help_text='example@nhs.net', max_length=254, unique=True)),
                ('cqc_registered_manager_id', models.CharField(help_text='1-XXXXXXXX', max_length=128)),
            ],
            bases=('management_interface.basemodel',),
        ),
        migrations.CreateModel(
            name='CareRecipient',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management_interface.basemodel')),
                ('nhs_number_hash', models.CharField(db_index=True, editable=False, max_length=128)),
                ('nhs_number', models.CharField(blank=True, max_length=32, null=True)),
                ('subscription_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('provider_reference_id', models.CharField(db_index=True, help_text='WANT45320482', max_length=128, unique=True)),
                ('care_provider_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_interface.careproviderlocation')),
            ],
            bases=('management_interface.basemodel',),
        ),
        migrations.AddField(
            model_name='careproviderlocation',
            name='registered_manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_interface.registeredmanager'),
        ),
    ]
