# Generated by Django 4.1.7 on 2023-03-10 08:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import management_interface.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareProviderLocation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Your Care Provider Branch Name", max_length=256)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="example@nhs.net",
                        max_length=254,
                        validators=[management_interface.models.SecureEmailValidator()],
                    ),
                ),
                ("ods_code", models.CharField(help_text="XXXABCD", max_length=16, unique=True)),
                ("cqc_location_id", models.CharField(help_text="1-110XXXXXXXX", max_length=128, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegisteredManager",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("given_name", models.CharField(db_index=True, help_text="Aislinn", max_length=256)),
                ("family_name", models.CharField(db_index=True, help_text="Mullen", max_length=256)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="example@nhs.net",
                        max_length=254,
                        unique=True,
                        validators=[management_interface.models.SecureEmailValidator()],
                    ),
                ),
                ("cqc_registered_manager_id", models.CharField(help_text="1-XXXXXXXX", max_length=128)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CareRecipient",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nhs_number_hash", models.CharField(db_index=True, editable=False, max_length=128)),
                (
                    "subscription_id",
                    models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=64, unique=True),
                ),
                (
                    "provider_reference_id",
                    models.CharField(db_index=True, help_text="XXX12345678", max_length=128, unique=True),
                ),
                ("nhs_number", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "care_provider_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="management_interface.careproviderlocation"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="careproviderlocation",
            name="registered_manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="management_interface.registeredmanager"
            ),
        ),
        migrations.AddField(
            model_name="careproviderlocation",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
